---
dist: trusty
addons:
  coverity_scan:
    project:
      description: Apache module for libmaxminddb
      name: maxmind/mod_maxminddb
    notification_email: dev-ci@maxmind.com
    build_command_prepend: make clean
    build_command: gcc -fpic -DSHARED_MODULE  -I/usr/include/apache2 -I/usr/include/apr-1.0 -I/usr/include/apr-1.0 -I/usr/include  -std=gnu99 -c src/mod_maxminddb.c
    branch_pattern: .*coverity.*
language: perl
perl:
  - '5.18'
env:
  global:
    - secure: SaZg9Tde8fwrRST4ik3S5isIRqevV49UiIpwyiAO5R7EBS3QrARGrAV3HUpkWPI+tvPFW98+WoC+CesX2rEV2mXRW8+7H+9sRcfDCQFzxQw0yUh/qjJjC/XSZNYb67LiP9Je8fSSpZfta4gn7MvJy4koFZlP/BKloVqUvxjydmk=
before_install:
  - cpanm Carton
  - git submodule update --init --recursive
  - git clone --recursive git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-mpm-prefork apache2-bin apache2 apache2-prefork-dev apache2-utils libapache2-mod-perl2
  - sudo apt-get install --assume-yes libtool libpcre3-dev libexpat1-dev libapache2-mod-security2 libjson-xs-perl
  - sudo mkdir /etc/apache2/logs
  - ./bootstrap
  - CFLAGS="-DMAXMINDDB_DEBUG=1 -std=c99 -Wall -Wextra -Werror -Wno-missing-field-initializers" ./configure
  - make
  - sudo make install
install:
  - cpanm --installdeps --notest .
script:
  - perl Makefile.PL -configure -httpd_conf setup/apache2.conf -src_dir /usr/lib/apache2/modules
  - mkdir t/logs
  - ./t/TEST -v
after_failure:
  - sudo apache2ctl -M
  - cat t/logs/error_log
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "HWyeOjwiDH9sXpzTbDcWMs/f7fa1ZIHCYJ7qcwLz81fKxvZ9o9+PFAXY3LZYBNahIxZu5HZafa/jHVdWqzzsLjHQGcwbbQ12/vbjD3EgJ5WrV9T6JReX8uAedvzd+xzuhzBB4CSWM420JP5cC/AzTnEZ2xz3aZHtX5HajUXYPmY=\n"
